theme: minima
title: Rayyan Zahid
author: rayyan zahid
email: contact@rayyanzahid.com
description: > # this means to ignore newlines until "baseurl:"
  This is Rayyan Zahid's website
# social links
twitter_username: Rayyanzahid # DO NOT include the @ character, or else the build will fail!
github_username:  RayyanZahid # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
